### ISSUE TITLE
Problem with JDK 7+8

### ISSUE THREAD

**Issue by jponge** [laurilehmijoki/s3_website#146]
Pushing with JDK 7 or 8 fails:

```
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: sun/management/ExtendedPlatformComponent
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:494)
	at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:112)
	at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:50)
	at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
	at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:330)
	at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:308)
	at com.amazonaws.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:239)
	at s3.website.S3$.awsS3Client(S3.scala:110)
	at s3.website.S3$S3Setting$$anonfun$apply$default$1$1.apply(S3.scala:223)
	at s3.website.S3$S3Setting$$anonfun$apply$default$1$1.apply(S3.scala:223)
	at s3.website.S3$$anonfun$resolveS3Files$1.apply(S3.scala:119)
	at s3.website.S3$$anonfun$resolveS3Files$1.apply(S3.scala:114)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Tested on Mac OS X Mavericks with Oracle JDKs. There is no issue with the old Apple JDK 6.

**Comment by laurilehmijoki** [comment]
I just [asked](https://github.com/aws/aws-sdk-java/issues/358) the AWS Java SDK team about this issue. Waiting for them to reply...

**Comment by laurilehmijoki** [comment]
Update: https://github.com/aws/aws-sdk-java/issues/358#issuecomment-73574427. @jponge can you respond to @david-at-aws directly?

**Comment by jponge** [comment]
I can confirm that a recent 8u40-ea build does not have the issue anymore. Thanks!
