### ISSUE TITLE
s3_website push error

### ISSUE THREAD

**Issue by Hesesses** [laurilehmijoki/s3_website#175]
Suddenly push command is not working anymore:

```
☁  web [master] s3_website push
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.8.0/s3_website.jar into /var/folders/1r/c37sxsfx0bsg1cqj7f3x56xc0000gn/T//s3_website-2.8.0.jar
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 403 Forbidden (OpenURI::HTTPError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/s3_website-2.8.0/bin/s3_website:238:in `block in download_jar'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/s3_website-2.8.0/bin/s3_website:237:in `download_jar'
	from /Library/Ruby/Gems/2.0.0/gems/s3_website-2.8.0/bin/s3_website:220:in `resolve_jar'
	from /Library/Ruby/Gems/2.0.0/gems/s3_website-2.8.0/bin/s3_website:115:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/s3_website-2.8.0/bin/s3_website:270:in `<top (required)>'
	from /usr/bin/s3_website:23:in `load'
	from /usr/bin/s3_website:23:in `<main>'
```

Any ideas?

**Comment by akiwarheit** [comment]
Same issue but different error log

```
keeboi@ubuntu:~/blog$ s3_website push
[info] The jar file is corrupted. (Expected checksum cf1a6f74b8eaceb16173937afc198952 but got d41d8cd98f00b204e9800998ecf8427e.)
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.11.0/s3_website.jar into /home/keeboi/.rvm/gems/ruby-2.2.1/gems/s3_website-2.11.0/s3_website-2.11.0.jar
/home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock': Connection reset by peer (Errno::ECONNRESET)
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:104:in `read'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:289:in `block in read_body_0'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:274:in `inflater'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:279:in `read_body_0'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:333:in `block (2 levels) in open_http'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1421:in `block (2 levels) in transport_request'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:162:in `reading_body'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1420:in `block in transport_request'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:324:in `block in open_http'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/s3_website-2.11.0/bin/s3_website:238:in `block in download_jar'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	from /home/keeboi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/s3_website-2.11.0/bin/s3_website:237:in `download_jar'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/s3_website-2.11.0/bin/s3_website:220:in `resolve_jar'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/s3_website-2.11.0/bin/s3_website:115:in `push'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/gems/s3_website-2.11.0/bin/s3_website:270:in `<top (required)>'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/bin/s3_website:23:in `load'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/bin/s3_website:23:in `<main>'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/keeboi/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by laurilehmijoki** [comment]
Maybe there's a network problem in trying to reach the host github.com? Does the problem persist?

**Comment by akiwarheit** [comment]
AWS was down awhile ago. My issue is fixed.

**Comment by laurilehmijoki** [comment]
Closing as willnotfix. Please reopen if needed.
