### ISSUE TITLE
Error after macOS Sierra upgrade

### ISSUE THREAD

**Issue by diegoscl** [laurilehmijoki/s3_website#241]
Hi there!

I upgrade macOS to Sierra some day ago and now i get the following error when tried to deploy my site:

`Macbook-Diego-Belmar-2:blog diego$ s3_website push
[info] Deploying /Users/diego/Sites/blog/_site/* to diego.web.blog
2016-09-26 13:41:17,509 [pool-1-thread-1] WARN  com.amazonaws.http.AmazonHttpClient -  Detected a possible problem with the current JVM version (1.6.0_65).  If you experience XML parsing problems using the SDK, try upgrading to a more recent JVM update.
[wait] Failed to fetch an object listing (Unable to execute HTTP request: diego.web.blog.s3-us-west-1.amazonaws.com). Trying again in 1 second.
[wait] Failed to fetch an object listing (Unable to execute HTTP request: diego.web.blog.s3-us-west-1.amazonaws.com). Trying again in 2 seconds.
[wait] Failed to fetch an object listing (Unable to execute HTTP request: diego.web.blog.s3-us-west-1.amazonaws.com). Trying again in 3 seconds.
[wait] Failed to fetch an object listing (Unable to execute HTTP request: diego.web.blog.s3-us-west-1.amazonaws.com). Trying again in 5 seconds.
Exception in thread "main" org.jruby.exceptions.RaiseException: (SyntaxError) <script>:2: invalid multibyte char (UTF-8)
	at s3.website.Ruby$.rubyRegexMatches(Ruby.scala:7)
	at s3.website.package$S3KeyRegex.matches(package.scala:60)
	at s3.website.model.Files$$anonfun$7$$anonfun$apply$9.apply(push.scala:164)
	at s3.website.model.Files$$anonfun$7$$anonfun$apply$9.apply(push.scala:164)
	at scala.collection.LinearSeqOptimized$class.exists(LinearSeqOptimized.scala:93)
	at scala.collection.immutable.List.exists(List.scala:84)
	at s3.website.model.Files$$anonfun$7.apply(push.scala:164)
	at s3.website.model.Files$$anonfun$7.apply(push.scala:164)
	at scala.Option.exists(Option.scala:240)
	at s3.website.model.Files$.s3$website$model$Files$$excludeFromUpload$1(push.scala:163)
	at s3.website.model.Files$$anonfun$listSiteFiles$2.apply(push.scala:173)
	at s3.website.model.Files$$anonfun$listSiteFiles$2.apply(push.scala:173)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
	at s3.website.model.Files$.listSiteFiles(push.scala:173)
	at s3.website.UploadHelper$.resolveDeletes(UploadHelper.scala:56)
	at s3.website.Push$$anonfun$7$$anonfun$apply$8.apply(Push.scala:98)
	at s3.website.Push$$anonfun$7$$anonfun$apply$8.apply(Push.scala:98)
	at scala.util.Either.fold(Either.scala:99)
	at s3.website.Push$$anonfun$7.apply(Push.scala:96)
	at s3.website.Push$$anonfun$7.apply(Push.scala:95)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
^C/Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/s3_website-2.15.1/bin/s3_website:147:in `system': Interrupt
	from /Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/s3_website-2.15.1/bin/s3_website:147:in `run_s3_website_jar'
	from /Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/s3_website-2.15.1/bin/s3_website:117:in `push'
	from /Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/diego/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/s3_website-2.15.1/bin/s3_website:274:in `<top (required)>'
	from /Users/diego/.rbenv/versions/2.3.1/bin/s3_website:22:in `load'
	from /Users/diego/.rbenv/versions/2.3.1/bin/s3_website:22:in `<main>'`

My machine have "Java for OS X 2015-001" and "Java 8 update 102" installed.

¿Anyone can help me? :/

**Comment by jhabdas** [comment]
I'm using the latest macOS. No problems here. Try updating Ruby yet?
