### ISSUE TITLE
ignore on server option

### ISSUE THREAD

**Issue by sathuer** [laurilehmijoki/s3_website#285]
s3_website.yml issue option
ignore_on_server:
  - upload

if it is exist Korean text file(upload/홍길동.txt) in folder ignore on server, error below

Exception in thread "main" org.jruby.exceptions.RaiseException: (SyntaxError) <script>:2: invalid multibyte char (UTF-8)
        at s3.website.Ruby$.rubyRegexMatches(Ruby.scala:7)
        at s3.website.package$S3KeyRegex.matches(package.scala:60)
        at s3.website.package$S3KeyRegexes$$anonfun$matches$1.apply(package.scala:93)
        at s3.website.package$S3KeyRegexes$$anonfun$matches$1.apply(package.scala:93)
        at scala.collection.Iterator$class.exists(Iterator.scala:768)
        at scala.collection.AbstractIterator.exists(Iterator.scala:1194)
        at scala.collection.IterableLike$class.exists(IterableLike.scala:77)
        at scala.collection.AbstractIterable.exists(Iterable.scala:54)
        at s3.website.package$S3KeyRegexes.matches(package.scala:92)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3$$anonfun$apply$5$$anonfun$apply$6$$anonfun$12.apply(UploadHelper.scala:67)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3$$anonfun$apply$5$$anonfun$apply$6$$anonfun$12.apply(UploadHelper.scala:67)
        at scala.Option.exists(Option.scala:240)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3$$anonfun$apply$5$$anonfun$apply$6.apply(UploadHelper.scala:67)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3$$anonfun$apply$5$$anonfun$apply$6.apply(UploadHelper.scala:66)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
        at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:278)
        at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3$$anonfun$apply$5.apply(UploadHelper.scala:66)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3$$anonfun$apply$5.apply(UploadHelper.scala:60)
        at scala.util.Either$RightProjection.map(Either.scala:535)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3.apply(UploadHelper.scala:60)
        at s3.website.UploadHelper$$anonfun$resolveDeletes$3.apply(UploadHelper.scala:58)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)

please, check this...

**Comment by laurilehmijoki** [comment]
What does your `locale` command say?

**Comment by sathuer** [comment]
It's **ko** of file's locale

**Comment by laurilehmijoki** [comment]
Will the problem disappear if you set the locale to UTF-8?

**Comment by sathuer** [comment]
Does s3_website has build option about locale? 

i'm sorry, I don't know that set the locale to UTF-8, 

how to set th locale to UTF-8?

please help me..

**Comment by laurilehmijoki** [comment]
Try googling. The answer may depend on your shell and operating system.
